# Generated by Django 5.1.2 on 2024-10-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
