# Generated by Django 5.1.2 on 2024-10-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_payment_deleted_at_payment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='staff_payment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
